// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

public interface ExportMetricValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExportMetricValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string metricName = 1;</code>
   */
  String getMetricName();
  /**
   * <code>string metricName = 1;</code>
   */
  com.google.protobuf.ByteString
      getMetricNameBytes();

  /**
   * <code>string entityName = 2;</code>
   */
  String getEntityName();
  /**
   * <code>string entityName = 2;</code>
   */
  com.google.protobuf.ByteString
      getEntityNameBytes();

  /**
   * <code>string entityId = 3;</code>
   */
  String getEntityId();
  /**
   * <code>string entityId = 3;</code>
   */
  com.google.protobuf.ByteString
      getEntityIdBytes();

  /**
   * <code>.ValueType type = 4;</code>
   */
  int getTypeValue();
  /**
   * <code>.ValueType type = 4;</code>
   */
  ValueType getType();

  /**
   * <code>int64 timeBucket = 5;</code>
   */
  long getTimeBucket();

  /**
   * <code>int64 longValue = 6;</code>
   */
  long getLongValue();

  /**
   * <code>double doubleValue = 7;</code>
   */
  double getDoubleValue();

  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  java.util.List<Long> getLongValuesList();
  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  int getLongValuesCount();
  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  long getLongValues(int index);
}
