// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

public interface ExportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExportResponse)
    com.google.protobuf.MessageOrBuilder {
}
