// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

/**
 * Protobuf type {@code ExportMetricValue}
 */
public  final class ExportMetricValue extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ExportMetricValue)
    ExportMetricValueOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ExportMetricValue.newBuilder() to construct.
  private ExportMetricValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ExportMetricValue() {
    metricName_ = "";
    entityName_ = "";
    entityId_ = "";
    type_ = 0;
    timeBucket_ = 0L;
    longValue_ = 0L;
    doubleValue_ = 0D;
    longValues_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ExportMetricValue(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            metricName_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            entityName_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            entityId_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 40: {

            timeBucket_ = input.readInt64();
            break;
          }
          case 48: {

            longValue_ = input.readInt64();
            break;
          }
          case 57: {

            doubleValue_ = input.readDouble();
            break;
          }
          case 64: {
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              longValues_ = new java.util.ArrayList<Long>();
              mutable_bitField0_ |= 0x00000080;
            }
            longValues_.add(input.readInt64());
            break;
          }
          case 66: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080) && input.getBytesUntilLimit() > 0) {
              longValues_ = new java.util.ArrayList<Long>();
              mutable_bitField0_ |= 0x00000080;
            }
            while (input.getBytesUntilLimit() > 0) {
              longValues_.add(input.readInt64());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        longValues_ = java.util.Collections.unmodifiableList(longValues_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MetricExporter.internal_static_ExportMetricValue_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MetricExporter.internal_static_ExportMetricValue_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ExportMetricValue.class, Builder.class);
  }

  private int bitField0_;
  public static final int METRICNAME_FIELD_NUMBER = 1;
  private volatile Object metricName_;
  /**
   * <code>string metricName = 1;</code>
   */
  public String getMetricName() {
    Object ref = metricName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      metricName_ = s;
      return s;
    }
  }
  /**
   * <code>string metricName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMetricNameBytes() {
    Object ref = metricName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      metricName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITYNAME_FIELD_NUMBER = 2;
  private volatile Object entityName_;
  /**
   * <code>string entityName = 2;</code>
   */
  public String getEntityName() {
    Object ref = entityName_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      entityName_ = s;
      return s;
    }
  }
  /**
   * <code>string entityName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEntityNameBytes() {
    Object ref = entityName_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      entityName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENTITYID_FIELD_NUMBER = 3;
  private volatile Object entityId_;
  /**
   * <code>string entityId = 3;</code>
   */
  public String getEntityId() {
    Object ref = entityId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs =
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      entityId_ = s;
      return s;
    }
  }
  /**
   * <code>string entityId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getEntityIdBytes() {
    Object ref = entityId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b =
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      entityId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_;
  /**
   * <code>.ValueType type = 4;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.ValueType type = 4;</code>
   */
  public ValueType getType() {
    ValueType result = ValueType.valueOf(type_);
    return result == null ? ValueType.UNRECOGNIZED : result;
  }

  public static final int TIMEBUCKET_FIELD_NUMBER = 5;
  private long timeBucket_;
  /**
   * <code>int64 timeBucket = 5;</code>
   */
  public long getTimeBucket() {
    return timeBucket_;
  }

  public static final int LONGVALUE_FIELD_NUMBER = 6;
  private long longValue_;
  /**
   * <code>int64 longValue = 6;</code>
   */
  public long getLongValue() {
    return longValue_;
  }

  public static final int DOUBLEVALUE_FIELD_NUMBER = 7;
  private double doubleValue_;
  /**
   * <code>double doubleValue = 7;</code>
   */
  public double getDoubleValue() {
    return doubleValue_;
  }

  public static final int LONGVALUES_FIELD_NUMBER = 8;
  private java.util.List<Long> longValues_;
  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  public java.util.List<Long>
      getLongValuesList() {
    return longValues_;
  }
  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  public int getLongValuesCount() {
    return longValues_.size();
  }
  /**
   * <code>repeated int64 longValues = 8;</code>
   */
  public long getLongValues(int index) {
    return longValues_.get(index);
  }
  private int longValuesMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getMetricNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, metricName_);
    }
    if (!getEntityNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, entityName_);
    }
    if (!getEntityIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, entityId_);
    }
    if (type_ != ValueType.LONG.getNumber()) {
      output.writeEnum(4, type_);
    }
    if (timeBucket_ != 0L) {
      output.writeInt64(5, timeBucket_);
    }
    if (longValue_ != 0L) {
      output.writeInt64(6, longValue_);
    }
    if (doubleValue_ != 0D) {
      output.writeDouble(7, doubleValue_);
    }
    if (getLongValuesList().size() > 0) {
      output.writeUInt32NoTag(66);
      output.writeUInt32NoTag(longValuesMemoizedSerializedSize);
    }
    for (int i = 0; i < longValues_.size(); i++) {
      output.writeInt64NoTag(longValues_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMetricNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, metricName_);
    }
    if (!getEntityNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, entityName_);
    }
    if (!getEntityIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, entityId_);
    }
    if (type_ != ValueType.LONG.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (timeBucket_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, timeBucket_);
    }
    if (longValue_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, longValue_);
    }
    if (doubleValue_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, doubleValue_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < longValues_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt64SizeNoTag(longValues_.get(i));
      }
      size += dataSize;
      if (!getLongValuesList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      longValuesMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ExportMetricValue)) {
      return super.equals(obj);
    }
    ExportMetricValue other = (ExportMetricValue) obj;

    boolean result = true;
    result = result && getMetricName()
        .equals(other.getMetricName());
    result = result && getEntityName()
        .equals(other.getEntityName());
    result = result && getEntityId()
        .equals(other.getEntityId());
    result = result && type_ == other.type_;
    result = result && (getTimeBucket()
        == other.getTimeBucket());
    result = result && (getLongValue()
        == other.getLongValue());
    result = result && (
        Double.doubleToLongBits(getDoubleValue())
        == Double.doubleToLongBits(
            other.getDoubleValue()));
    result = result && getLongValuesList()
        .equals(other.getLongValuesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + METRICNAME_FIELD_NUMBER;
    hash = (53 * hash) + getMetricName().hashCode();
    hash = (37 * hash) + ENTITYNAME_FIELD_NUMBER;
    hash = (53 * hash) + getEntityName().hashCode();
    hash = (37 * hash) + ENTITYID_FIELD_NUMBER;
    hash = (53 * hash) + getEntityId().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TIMEBUCKET_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimeBucket());
    hash = (37 * hash) + LONGVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLongValue());
    hash = (37 * hash) + DOUBLEVALUE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        Double.doubleToLongBits(getDoubleValue()));
    if (getLongValuesCount() > 0) {
      hash = (37 * hash) + LONGVALUES_FIELD_NUMBER;
      hash = (53 * hash) + getLongValuesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ExportMetricValue parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricValue parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricValue parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricValue parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricValue parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ExportMetricValue parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ExportMetricValue parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportMetricValue parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportMetricValue parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ExportMetricValue parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ExportMetricValue parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ExportMetricValue parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ExportMetricValue prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ExportMetricValue}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ExportMetricValue)
      ExportMetricValueOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetricExporter.internal_static_ExportMetricValue_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetricExporter.internal_static_ExportMetricValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ExportMetricValue.class, Builder.class);
    }

    // Construct using com.tom.service.grpc.ExportMetricValue.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      metricName_ = "";

      entityName_ = "";

      entityId_ = "";

      type_ = 0;

      timeBucket_ = 0L;

      longValue_ = 0L;

      doubleValue_ = 0D;

      longValues_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MetricExporter.internal_static_ExportMetricValue_descriptor;
    }

    public ExportMetricValue getDefaultInstanceForType() {
      return ExportMetricValue.getDefaultInstance();
    }

    public ExportMetricValue build() {
      ExportMetricValue result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public ExportMetricValue buildPartial() {
      ExportMetricValue result = new ExportMetricValue(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.metricName_ = metricName_;
      result.entityName_ = entityName_;
      result.entityId_ = entityId_;
      result.type_ = type_;
      result.timeBucket_ = timeBucket_;
      result.longValue_ = longValue_;
      result.doubleValue_ = doubleValue_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        longValues_ = java.util.Collections.unmodifiableList(longValues_);
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.longValues_ = longValues_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ExportMetricValue) {
        return mergeFrom((ExportMetricValue)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ExportMetricValue other) {
      if (other == ExportMetricValue.getDefaultInstance()) return this;
      if (!other.getMetricName().isEmpty()) {
        metricName_ = other.metricName_;
        onChanged();
      }
      if (!other.getEntityName().isEmpty()) {
        entityName_ = other.entityName_;
        onChanged();
      }
      if (!other.getEntityId().isEmpty()) {
        entityId_ = other.entityId_;
        onChanged();
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getTimeBucket() != 0L) {
        setTimeBucket(other.getTimeBucket());
      }
      if (other.getLongValue() != 0L) {
        setLongValue(other.getLongValue());
      }
      if (other.getDoubleValue() != 0D) {
        setDoubleValue(other.getDoubleValue());
      }
      if (!other.longValues_.isEmpty()) {
        if (longValues_.isEmpty()) {
          longValues_ = other.longValues_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureLongValuesIsMutable();
          longValues_.addAll(other.longValues_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ExportMetricValue parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ExportMetricValue) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object metricName_ = "";
    /**
     * <code>string metricName = 1;</code>
     */
    public String getMetricName() {
      Object ref = metricName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        metricName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string metricName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMetricNameBytes() {
      Object ref = metricName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        metricName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string metricName = 1;</code>
     */
    public Builder setMetricName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      metricName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string metricName = 1;</code>
     */
    public Builder clearMetricName() {

      metricName_ = getDefaultInstance().getMetricName();
      onChanged();
      return this;
    }
    /**
     * <code>string metricName = 1;</code>
     */
    public Builder setMetricNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      metricName_ = value;
      onChanged();
      return this;
    }

    private Object entityName_ = "";
    /**
     * <code>string entityName = 2;</code>
     */
    public String getEntityName() {
      Object ref = entityName_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        entityName_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string entityName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEntityNameBytes() {
      Object ref = entityName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        entityName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entityName = 2;</code>
     */
    public Builder setEntityName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      entityName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entityName = 2;</code>
     */
    public Builder clearEntityName() {

      entityName_ = getDefaultInstance().getEntityName();
      onChanged();
      return this;
    }
    /**
     * <code>string entityName = 2;</code>
     */
    public Builder setEntityNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      entityName_ = value;
      onChanged();
      return this;
    }

    private Object entityId_ = "";
    /**
     * <code>string entityId = 3;</code>
     */
    public String getEntityId() {
      Object ref = entityId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        entityId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string entityId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEntityIdBytes() {
      Object ref = entityId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        entityId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string entityId = 3;</code>
     */
    public Builder setEntityId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }

      entityId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string entityId = 3;</code>
     */
    public Builder clearEntityId() {

      entityId_ = getDefaultInstance().getEntityId();
      onChanged();
      return this;
    }
    /**
     * <code>string entityId = 3;</code>
     */
    public Builder setEntityIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

      entityId_ = value;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.ValueType type = 4;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.ValueType type = 4;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ValueType type = 4;</code>
     */
    public ValueType getType() {
      ValueType result = ValueType.valueOf(type_);
      return result == null ? ValueType.UNRECOGNIZED : result;
    }
    /**
     * <code>.ValueType type = 4;</code>
     */
    public Builder setType(ValueType value) {
      if (value == null) {
        throw new NullPointerException();
      }

      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ValueType type = 4;</code>
     */
    public Builder clearType() {

      type_ = 0;
      onChanged();
      return this;
    }

    private long timeBucket_ ;
    /**
     * <code>int64 timeBucket = 5;</code>
     */
    public long getTimeBucket() {
      return timeBucket_;
    }
    /**
     * <code>int64 timeBucket = 5;</code>
     */
    public Builder setTimeBucket(long value) {

      timeBucket_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timeBucket = 5;</code>
     */
    public Builder clearTimeBucket() {

      timeBucket_ = 0L;
      onChanged();
      return this;
    }

    private long longValue_ ;
    /**
     * <code>int64 longValue = 6;</code>
     */
    public long getLongValue() {
      return longValue_;
    }
    /**
     * <code>int64 longValue = 6;</code>
     */
    public Builder setLongValue(long value) {

      longValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 longValue = 6;</code>
     */
    public Builder clearLongValue() {

      longValue_ = 0L;
      onChanged();
      return this;
    }

    private double doubleValue_ ;
    /**
     * <code>double doubleValue = 7;</code>
     */
    public double getDoubleValue() {
      return doubleValue_;
    }
    /**
     * <code>double doubleValue = 7;</code>
     */
    public Builder setDoubleValue(double value) {

      doubleValue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double doubleValue = 7;</code>
     */
    public Builder clearDoubleValue() {

      doubleValue_ = 0D;
      onChanged();
      return this;
    }

    private java.util.List<Long> longValues_ = java.util.Collections.emptyList();
    private void ensureLongValuesIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        longValues_ = new java.util.ArrayList<Long>(longValues_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public java.util.List<Long>
        getLongValuesList() {
      return java.util.Collections.unmodifiableList(longValues_);
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public int getLongValuesCount() {
      return longValues_.size();
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public long getLongValues(int index) {
      return longValues_.get(index);
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public Builder setLongValues(
        int index, long value) {
      ensureLongValuesIsMutable();
      longValues_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public Builder addLongValues(long value) {
      ensureLongValuesIsMutable();
      longValues_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public Builder addAllLongValues(
        Iterable<? extends Long> values) {
      ensureLongValuesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, longValues_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int64 longValues = 8;</code>
     */
    public Builder clearLongValues() {
      longValues_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ExportMetricValue)
  }

  // @@protoc_insertion_point(class_scope:ExportMetricValue)
  private static final ExportMetricValue DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ExportMetricValue();
  }

  public static ExportMetricValue getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ExportMetricValue>
      PARSER = new com.google.protobuf.AbstractParser<ExportMetricValue>() {
    public ExportMetricValue parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ExportMetricValue(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ExportMetricValue> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ExportMetricValue> getParserForType() {
    return PARSER;
  }

  public ExportMetricValue getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

