// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

public final class MetricExporter {
  private MetricExporter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExportMetricValue_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExportMetricValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscriptionsResp_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscriptionsResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubscriptionReq_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubscriptionReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ExportResponse_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ExportResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025metric-exporter.proto\"\267\001\n\021ExportMetric" +
      "Value\022\022\n\nmetricName\030\001 \001(\t\022\022\n\nentityName\030" +
      "\002 \001(\t\022\020\n\010entityId\030\003 \001(\t\022\030\n\004type\030\004 \001(\0162\n." +
      "ValueType\022\022\n\ntimeBucket\030\005 \001(\003\022\021\n\tlongVal" +
      "ue\030\006 \001(\003\022\023\n\013doubleValue\030\007 \001(\001\022\022\n\nlongVal" +
      "ues\030\010 \003(\003\"(\n\021SubscriptionsResp\022\023\n\013metric" +
      "Names\030\001 \003(\t\"\021\n\017SubscriptionReq\"\020\n\016Export" +
      "Response*1\n\tValueType\022\010\n\004LONG\020\000\022\n\n\006DOUBL" +
      "E\020\001\022\016\n\nMULTI_LONG\020\0022\200\001\n\023MetricExportServ" +
      "ice\0221\n\006export\022\022.ExportMetricValue\032\017.Expo",
      "rtResponse\"\000(\001\0226\n\014subscription\022\020.Subscri" +
      "ptionReq\032\022.SubscriptionsResp\"\000B\037\n\033com." +
      "tom.service.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ExportMetricValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ExportMetricValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExportMetricValue_descriptor,
        new String[] { "MetricName", "EntityName", "EntityId", "Type", "TimeBucket", "LongValue", "DoubleValue", "LongValues", });
    internal_static_SubscriptionsResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SubscriptionsResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscriptionsResp_descriptor,
        new String[] { "MetricNames", });
    internal_static_SubscriptionReq_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SubscriptionReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubscriptionReq_descriptor,
        new String[] { });
    internal_static_ExportResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ExportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ExportResponse_descriptor,
        new String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
