// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

public interface SubscriptionsRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscriptionsResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string metricNames = 1;</code>
   */
  java.util.List<String>
      getMetricNamesList();
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  int getMetricNamesCount();
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  String getMetricNames(int index);
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  com.google.protobuf.ByteString
      getMetricNamesBytes(int index);
}
