// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

public interface SubscriptionReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscriptionReq)
    com.google.protobuf.MessageOrBuilder {
}
