// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

/**
 * Protobuf type {@code SubscriptionsResp}
 */
public  final class SubscriptionsResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubscriptionsResp)
    SubscriptionsRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubscriptionsResp.newBuilder() to construct.
  private SubscriptionsResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubscriptionsResp() {
    metricNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubscriptionsResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              metricNames_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            metricNames_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        metricNames_ = metricNames_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MetricExporter.internal_static_SubscriptionsResp_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MetricExporter.internal_static_SubscriptionsResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SubscriptionsResp.class, Builder.class);
  }

  public static final int METRICNAMES_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList metricNames_;
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getMetricNamesList() {
    return metricNames_;
  }
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  public int getMetricNamesCount() {
    return metricNames_.size();
  }
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  public String getMetricNames(int index) {
    return metricNames_.get(index);
  }
  /**
   * <code>repeated string metricNames = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMetricNamesBytes(int index) {
    return metricNames_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < metricNames_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, metricNames_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < metricNames_.size(); i++) {
        dataSize += computeStringSizeNoTag(metricNames_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMetricNamesList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SubscriptionsResp)) {
      return super.equals(obj);
    }
    SubscriptionsResp other = (SubscriptionsResp) obj;

    boolean result = true;
    result = result && getMetricNamesList()
        .equals(other.getMetricNamesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getMetricNamesCount() > 0) {
      hash = (37 * hash) + METRICNAMES_FIELD_NUMBER;
      hash = (53 * hash) + getMetricNamesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SubscriptionsResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscriptionsResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscriptionsResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscriptionsResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscriptionsResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SubscriptionsResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SubscriptionsResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscriptionsResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscriptionsResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SubscriptionsResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SubscriptionsResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SubscriptionsResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SubscriptionsResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubscriptionsResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubscriptionsResp)
      SubscriptionsRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MetricExporter.internal_static_SubscriptionsResp_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MetricExporter.internal_static_SubscriptionsResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SubscriptionsResp.class, Builder.class);
    }

    // Construct using com.tom.service.grpc.SubscriptionsResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      metricNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MetricExporter.internal_static_SubscriptionsResp_descriptor;
    }

    public SubscriptionsResp getDefaultInstanceForType() {
      return SubscriptionsResp.getDefaultInstance();
    }

    public SubscriptionsResp build() {
      SubscriptionsResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SubscriptionsResp buildPartial() {
      SubscriptionsResp result = new SubscriptionsResp(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        metricNames_ = metricNames_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.metricNames_ = metricNames_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SubscriptionsResp) {
        return mergeFrom((SubscriptionsResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SubscriptionsResp other) {
      if (other == SubscriptionsResp.getDefaultInstance()) return this;
      if (!other.metricNames_.isEmpty()) {
        if (metricNames_.isEmpty()) {
          metricNames_ = other.metricNames_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureMetricNamesIsMutable();
          metricNames_.addAll(other.metricNames_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SubscriptionsResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SubscriptionsResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList metricNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureMetricNamesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        metricNames_ = new com.google.protobuf.LazyStringArrayList(metricNames_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getMetricNamesList() {
      return metricNames_.getUnmodifiableView();
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public int getMetricNamesCount() {
      return metricNames_.size();
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public String getMetricNames(int index) {
      return metricNames_.get(index);
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMetricNamesBytes(int index) {
      return metricNames_.getByteString(index);
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public Builder setMetricNames(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMetricNamesIsMutable();
      metricNames_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public Builder addMetricNames(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureMetricNamesIsMutable();
      metricNames_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public Builder addAllMetricNames(
        Iterable<String> values) {
      ensureMetricNamesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, metricNames_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public Builder clearMetricNames() {
      metricNames_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string metricNames = 1;</code>
     */
    public Builder addMetricNamesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureMetricNamesIsMutable();
      metricNames_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubscriptionsResp)
  }

  // @@protoc_insertion_point(class_scope:SubscriptionsResp)
  private static final SubscriptionsResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SubscriptionsResp();
  }

  public static SubscriptionsResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscriptionsResp>
      PARSER = new com.google.protobuf.AbstractParser<SubscriptionsResp>() {
    public SubscriptionsResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubscriptionsResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubscriptionsResp> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SubscriptionsResp> getParserForType() {
    return PARSER;
  }

  public SubscriptionsResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

