// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: metric-exporter.proto

package com.tom.service.grpc;

/**
 * Protobuf enum {@code ValueType}
 */
public enum ValueType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>LONG = 0;</code>
   */
  LONG(0),
  /**
   * <code>DOUBLE = 1;</code>
   */
  DOUBLE(1),
  /**
   * <code>MULTI_LONG = 2;</code>
   */
  MULTI_LONG(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>LONG = 0;</code>
   */
  public static final int LONG_VALUE = 0;
  /**
   * <code>DOUBLE = 1;</code>
   */
  public static final int DOUBLE_VALUE = 1;
  /**
   * <code>MULTI_LONG = 2;</code>
   */
  public static final int MULTI_LONG_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static ValueType valueOf(int value) {
    return forNumber(value);
  }

  public static ValueType forNumber(int value) {
    switch (value) {
      case 0: return LONG;
      case 1: return DOUBLE;
      case 2: return MULTI_LONG;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ValueType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ValueType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ValueType>() {
          public ValueType findValueByNumber(int number) {
            return ValueType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return MetricExporter.getDescriptor().getEnumTypes().get(0);
  }

  private static final ValueType[] VALUES = values();

  public static ValueType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ValueType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ValueType)
}

